#macro PARAR "PARAR"
#macro ATACAR "ATACAR"
#macro MOVER "MOVER"
#macro RECARRECAR "RECARRECAR"

#macro LANTERNA "LANTERNA"
#macro PISTOLA "PISTOLA"
#macro RIFLE "RIFLE"
#macro ESPINGARDA "ESPINGARDA"